- kind: environment
  name: dev
  data:
    type: parquet
    path: s3a://cortex-examples/reviews.parquet
    schema:
      - parquet_column_name: review
        raw_column_name: review
      - parquet_column_name: label
        raw_column_name: label
