apiVersion: v1
name: sidecarInjectorWebhook
version: 1.2.2
appVersion: 1.2.2
tillerVersion: ">=2.7.2"
description: Helm chart for sidecar injector webhook deployment
keywords:
  - istio
  - sidecarInjectorWebhook
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
