name: base
channels:
    - defaults
    - conda-forge
dependencies:
    - conda-forge::python=3.6.9 
    - pip
    - pip:
        - -r file:lib/requirements.txt
        - -r file:serve/requirements.txt