# permissions for end users to view realtimeapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: realtimeapi-viewer-role
rules:
- apiGroups:
  - api.cortex.dev
  resources:
  - realtimeapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.cortex.dev
  resources:
  - realtimeapis/status
  verbs:
  - get
