apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-init-admin-role-binding-{{ .Release.Namespace }}
  labels:
    app: istio-init
    istio: init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-init-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-init-service-account
    namespace: {{ .Release.Namespace }}
