{{- if .Values.certmanager.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-crd-certmanager-11
data:
  crd-certmanager-11.yaml: |-
{{.Files.Get "files/crd-certmanager-11.yaml" | printf "%s" | indent 4}}
{{- end }}
