{{- if .Values.certmanager.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: istio-init-crd-certmanager-11
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: istio-init-service-account
      containers:
      - name: istio-init-crd-certmanager-11
        image: "{{ .Values.global.hub }}/kubectl:{{ .Values.global.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        volumeMounts:
        - name: crd-certmanager-11
          mountPath: /etc/istio/crd-certmanager-11
          readOnly: true
        command: ["kubectl",  "apply", "-f", "/etc/istio/crd-certmanager-11/crd-certmanager-11.yaml"]
      volumes:
      - name: crd-certmanager-11
        configMap:
          name: istio-crd-certmanager-11
      restartPolicy: OnFailure
{{- end }}
