# Copyright 2020 Cortex Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import List, Any

import os
import time
import threading as td


class ReadWriteLock:
    """
    Locking object allowing for write once, read many.

    The lock cannot be acquired multiple times in a single thread without its paired release call.
    """

    def __init__(self):
        self._read_allowed = td.Condition(td.RLock())
        self._readers = []
        self._writers = []

    def acquire(self, mode: str) -> bool:
        """
        Acquire a lock.

        Args:
            mode: "r" for read lock, "w" for write lock.

        Returns:
            Whether the mode was valid or not.
        """
        if mode == "r":
            self._read_allowed.acquire()
            try:
                while len(self._writers) > 0:
                    self._read_allowed.wait()
            finally:
                self._readers.append(td.get_ident())
                self._read_allowed.release()

        elif mode == "w":
            self._read_allowed.acquire()
            self._writers.append(td.get_ident())
            while len(self._readers) > 0:
                self._read_allowed.wait()
        else:
            return False

        return True

    def release(self, mode: str) -> bool:
        """
        Releases a lock.

        Args:
            mode: "r" for read lock, "w" for write lock.

        Returns:
            Whether the mode was valid or not.
        """
        if mode == "r":
            self._read_allowed.acquire()
            try:
                if not len(self._readers) - 1:
                    self._read_allowed.notifyAll()
            finally:
                self._readers.remove(td.get_ident())
                self._read_allowed.release()

        elif mode == "w":
            self._writers.remove(td.get_ident())
            self._read_allowed.notifyAll()
            self._read_allowed.release()

        else:
            return False

        return True


class ReadLock:
    """
    To be used as:

    rw_lock = ReadWriteLock()
    with ReadLock(rw_lock):
        # code
    """

    def __init__(self, lock: ReadWriteLock):
        self._lock = lock

    def __enter__(self):
        self._lock.acquire("r")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self_lock.release("r")
        return False


class WriteLock:
    """
    To be used as:

    rw_lock = ReadWriteLock()
    with WriteLock(rw_lock):
        # code
    """

    def __init__(self, lock: ReadWriteLock):
        self._lock = lock

    def __enter__(self):
        self._lock.acquire("w")
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self_lock.release("w")
        return False


class ModelsDict:
    """
    A class to hold models in memory.

    For a model to be removed from memory, it must not hold any references to the model outside this class.
    """

    def __init__(self):
        self._models = {}
        self._locks = {}

    def has_model(self, model: str, version: str) -> bool:
        return self.get_model(model, version) is not None

    def get_model(self, name: str, version: str) -> Any:
        model_id = f"{name}-{version}"
        try:
            self._locks[model_id].acquire()
        except:
            return None
        model = self._models[model_id]
        self._locks[model_id].release()

        return model

    def remove_model(self, name: str, version: str) -> None:
        model_id = f"{name}-{version}"
        try:
            self._locks[model_id].acquire()
        except:
            return
        del self._models[model_id]
        self._locks[model_id].release()

    def load_model(self, model: Any, name: str, version: str) -> None:
        model_id = f"{name}-{version}"
        try:
            self._locks[model_id].acquire()
        except:
            lock = td.Lock()
            lock_id = id(lock)
            self._locks[model_id] = lock
            self._locks[model_id].acquire()
            if id(self._locks[model_id]) is not lock_id:
                self._locks[model_id].release()
                raise RuntimeException("caught lock generated by another thread; retry")

        self._models[model_id] = model
        self._locks[model_id].release()

    def get_model_names(self) -> List[str]:
        model_names = [model_name.split("-") for model_name in self._models.keys()]
        return list(set(model_names))

    def get_model_versions(self, model_name) -> List[str]:
        return [model.split("-")[1] for model in models if model.startswith(model_name)]


class ModelLRU:
    def __init__(
        self, in_memory_tag: str = "mem", on_disk_tag: str = "disk",
    ):
        pass
