# Copyright 2019 Cortex Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CORTEX_CLUSTER
  region: $CORTEX_REGION
  version: "1.14"

nodeGroups:
  - name: ng-1
    instanceType: $CORTEX_NODE_TYPE
    minSize: $CORTEX_NODES_MIN
    maxSize: $CORTEX_NODES_MAX
    desiredCapacity: $CORTEX_NODES_MIN
    ami: auto
    iam:
      withAddonPolicies:
        autoScaler: true
    kubeletExtraConfig:
      kubeReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      kubeReservedCgroup: /kube-reserved
      systemReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      evictionHard:
        memory.available:  200Mi
        nodefs.available: 5%
