# Copyright 2019 Cortex Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $CORTEX_CLUSTER_NAME
  region: $CORTEX_REGION
  version: "1.14"

nodeGroups:
  - name: ng-cortex-operator
    instanceType: t3.medium
    availabilityZones: $CORTEX_AVAILABILITY_ZONES
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    ami: auto
    iam:
      withAddonPolicies:
        autoScaler: true
    kubeletExtraConfig:
      kubeReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      kubeReservedCgroup: /kube-reserved
      systemReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      evictionHard:
        memory.available:  200Mi
        nodefs.available: 5%

  - name: ng-cortex-worker
    instanceType: mixed
    availabilityZones: $CORTEX_AVAILABILITY_ZONES
    volumeSize: $CORTEX_INSTANCE_VOLUME_SIZE
    minSize: $CORTEX_MIN_INSTANCES
    maxSize: $CORTEX_MAX_INSTANCES
    desiredCapacity: $CORTEX_DESIRED_INSTANCES
    ami: auto
    iam:
      withAddonPolicies:
        autoScaler: true
    instancesDistribution:
      instanceTypes: $CORTEX_SPOT_CONFIG_INSTANCE_DISTRIBUTION
      maxPrice: $CORTEX_SPOT_CONFIG_MAX_PRICE
      onDemandBaseCapacity: $CORTEX_SPOT_CONFIG_ON_DEMAND_BASE_CAPACITY
      onDemandPercentageAboveBaseCapacity: $CORTEX_SPOT_CONFIG_ON_DEMAND_PERCENTAGE_ABOVE_BASE_CAPACITY
      spotInstancePools: $CORTEX_SPOT_CONFIG_INSTANCE_POOLS
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/node-template/label/workload: "true"
    labels:
      lifecycle: Ec2Spot
      workload: "true"
    taints:
      workload: "true:NoSchedule"
    kubeletExtraConfig:
      kubeReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      kubeReservedCgroup: /kube-reserved
      systemReserved:
        cpu: 150m
        memory: 300Mi
        ephemeral-storage: 1Gi
      evictionHard:
        memory.available: 200Mi
        nodefs.available: 5%
