- kind: model
  name: dnn
  estimator_path: implementations/models/dnn.py
  target_column: @label
  input: @image_pixels
  hparams:
    input_shape: [784]
    learning_rate: 0.01
    hidden_units: [100, 200]
  data_partition_ratio:
    training: 0.7
    evaluation: 0.3

- kind: model
  name: conv
  estimator_path: implementations/models/custom.py
  target_column: @label
  input: @image_pixels
  hparams:
    layer_type: conv
    learning_rate: 0.01
    input_shape: [28, 28, 1]
    output_shape: [10]
    kernel_size: 4
    hidden_units: [10, 10, 10]
  data_partition_ratio:
    training: 0.7
    evaluation: 0.3
  training:
    batch_size: 64
    num_epochs: 5


- kind: model
  name: t2t
  estimator_path: implementations/models/t2t.py
  target_column: @label
  input: @image_pixels
  prediction_key: outputs
  hparams:
    input_shape: [28, 28, 1]
  data_partition_ratio:
    training: 0.7
    evaluation: 0.3
  training:
    batch_size: 64
    num_steps: 5000
