{
 "title": "BatchAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "api_name",
    "label": "API Name",
    "query": {
     "query": "label_values({__name__=~\"cortex_batch_.+\"}, api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">BatchAPI</h1>\n"
   }
  },
  {
   "title": "# Succeeded Batches",
   "type": "graph",
   "description": "Number of succeeded batches for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_batch_succeeded{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "# Failed Batches",
   "type": "graph",
   "description": "Number of failed batches for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_batch_failed{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Average Time per Batch",
   "type": "graph",
   "description": "Average time per batch for an API",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_time_per_batch_sum{api_name=~\"$api_name\"}) by (api_name) / sum(cortex_time_per_batch_count{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  }
 ]
}