{
 "title": "RealtimeAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "api_name",
    "label": "API Name",
    "query": {
     "query": "label_values(cortex_in_flight_requests{api_kind=\"RealtimeAPI\"}, api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">RealtimeAPI</h1>"
   }
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Request rate, computed over every minute, of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "graph",
   "description": "Active in-flight requests for an API.\n\nNote: In-flight requests are recorded every 10 seconds, which will correspond to the minimum resolution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_in_flight_requests{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 2XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"2.*\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Active Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(cortex_in_flight_requests{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 4XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"4.+\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 5XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"5.+\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "graph",
   "description": "99th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "graph",
   "description": "90th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "graph",
   "description": "50th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "Average latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}