- kind: deployment
  name: iris

- kind: environment
  name: dev
  data:
    type: csv
    path: s3a://cortex-examples/iris.csv
    schema: [@sepal_length, @sepal_width, @petal_length, @petal_width, @class]

- kind: model
  name: dnn
  estimator: cortex.dnn_classifier
  target_column: @class
  input:
    numeric_columns: [@sepal_length, @sepal_width, @petal_length, @petal_width]
    target_vocab: ["Iris-setosa", "Iris-versicolor", "Iris-virginica"]
  hparams:
    hidden_units: [4, 2]
  training:
    batch_size: 10
    num_steps: 1000

- kind: api
  name: iris-type
  model: @dnn
  compute:
    replicas: 1
