# Copyright 2019 Cortex Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import consts

"""
HOW TO GENERATE CONTEXT

1. cx deploy
2. get a path to a context
3. ssh into a docker container (spark or tf_train)
docker run -it --entrypoint "/bin/bash" cortexlabs/spark
4. run the following in python3 shell

from lib import util
from lib.storage import S3

bucket = "cortex-cluster-<name>"
key = "apps/<app-name>/contexts/<context-id>.msgpack"
S3(bucket, client_config={}).get_msgpack(key)

5. udpate path of any impl_keys being used to /<impl_type>/<impl> e.g. /transformers/normalize.py
6. delete images in cortex_config
"""


def get(input_data_path):
    raw_ctx["environment_data"]["csv_data"]["path"] = input_data_path
    raw_ctx["cortex_config"]["api_version"] = consts.CORTEX_VERSION

    return raw_ctx


raw_ctx = {
    "status_prefix": "apps/insurance/resource_statuses",
    "apis": {
        "cost": {
            "index": 0,
            "tags": {},
            "file_path": "resources/apis.yaml",
            "id": "f308835ba4bc05edfa9043b1126795713024a2ef20776d4a5da155923398098",
            "name": "cost",
            "model": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31ddnn",
            "embed": None,
            "path": "/insurance/cost",
            "compute": {"replicas": 1, "mem": None, "gpu": 0, "cpu": None},
            "resource_type": "api",
            "workload_id": "byyzqwf8ko33fbkfsqbu",
        }
    },
    "transformed_columns": {
        "charges_normalized": {
            "index": 10,
            "transformer_path": None,
            "id": "2efa40387954c03ae7223bc7ec51ea48158d72aaa773f4f92823ac3384bc21f",
            "input": {
                "stddev": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges_stddev",
                "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges",
                "mean": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges_mean",
            },
            "workload_id": "f8tzufenx064auff8m0m",
            "type": "FLOAT_COLUMN",
            "tags": {},
            "file_path": "resources/features.yaml",
            "embed": None,
            "resource_type": "transformed_column",
            "compute": {
                "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                "driver_mem_overhead": None,
                "executor_mem_overhead": None,
                "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                "executors": 1,
                "mem_overhead_factor": None,
                "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
            },
            "transformer": "cortex.normalize",
            "name": "charges_normalized",
        }
    },
    "dataset_version": "2019-06-26-14-08-53-326265",
    "transformers": {
        "cortex.normalize": {
            "impl_key": "/transformers/normalize.py",
            "index": 1,
            "file_path": "/home/ubuntu/src/github.com/cortexlabs/cortex/pkg/transformers/transformers.yaml",
            "id": "0dcf14b7b6208633b8805b29eb564f860736a07691176095fd4f19aa5ef75ab",
            "input": {
                "_max_count": None,
                "_type": {
                    "stddev": {
                        "_max_count": None,
                        "_type": "INT|FLOAT",
                        "_default": None,
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": False,
                    },
                    "col": {
                        "_max_count": None,
                        "_type": "FLOAT_COLUMN|INT_COLUMN",
                        "_default": None,
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": False,
                    },
                    "mean": {
                        "_max_count": None,
                        "_type": "INT|FLOAT",
                        "_default": None,
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": False,
                    },
                },
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "embed": None,
            "path": "normalize.py",
            "resource_type": "transformer",
            "output_type": "FLOAT_COLUMN",
            "namespace": "cortex",
            "name": "normalize",
        }
    },
    "constants": {},
    "key": "apps/insurance/contexts/0d8a4cae897b48939e171ae4bb392478f9c5828d05dba2477ffc7f431630119.msgpack",
    "app": {
        "id": "64e8937abc6d71cf2d2f0fe05e52c33666883443ae4e8af7924c71198caa1f9",
        "name": "insurance",
    },
    "estimators": {
        "cortex.dnn_regressor": {
            "impl_key": "estimators/e6caca9ac002c71908ef329c0121447f92fe10ab73650b1a7195ffb1963024a.py",
            "index": 1,
            "id": "92b9b92727f6f86af3931d0bec4372660e82f9662e35d824a672f0df9752751",
            "input": {
                "_max_count": None,
                "_type": {
                    "categorical_columns_with_hash_bucket": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": {
                                    "weight_column": {
                                        "_max_count": None,
                                        "_type": "INT_COLUMN|FLOAT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "hash_bucket_size": {
                                        "_max_count": None,
                                        "_type": "INT",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                    "embedding_size": {
                                        "_max_count": None,
                                        "_type": "INT",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "col": {
                                        "_max_count": None,
                                        "_type": "STRING_COLUMN|INT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                },
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": [],
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    },
                    "categorical_columns_with_identity": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": {
                                    "num_classes": {
                                        "_max_count": None,
                                        "_type": "INT",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                    "embedding_size": {
                                        "_max_count": None,
                                        "_type": "INT",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "weight_column": {
                                        "_max_count": None,
                                        "_type": "INT_COLUMN|FLOAT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "col": {
                                        "_max_count": None,
                                        "_type": "INT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                },
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": [],
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    },
                    "bucketized_columns": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": {
                                    "boundaries": {
                                        "_max_count": None,
                                        "_type": [
                                            {
                                                "_max_count": None,
                                                "_type": "FLOAT",
                                                "_default": None,
                                                "_min_count": None,
                                                "_allow_null": False,
                                                "_optional": False,
                                            }
                                        ],
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                    "col": {
                                        "_max_count": None,
                                        "_type": "INT_COLUMN|FLOAT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                },
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": [],
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    },
                    "categorical_columns_with_vocab": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": {
                                    "vocab": {
                                        "_max_count": None,
                                        "_type": [
                                            {
                                                "_max_count": None,
                                                "_type": "STRING|INT",
                                                "_default": None,
                                                "_min_count": None,
                                                "_allow_null": False,
                                                "_optional": False,
                                            }
                                        ],
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                    "embedding_size": {
                                        "_max_count": None,
                                        "_type": "INT",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "weight_column": {
                                        "_max_count": None,
                                        "_type": "INT_COLUMN|FLOAT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": True,
                                    },
                                    "col": {
                                        "_max_count": None,
                                        "_type": "STRING_COLUMN|INT_COLUMN",
                                        "_default": None,
                                        "_min_count": None,
                                        "_allow_null": False,
                                        "_optional": False,
                                    },
                                },
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": [],
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    },
                    "numeric_columns": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": "INT_COLUMN|FLOAT_COLUMN",
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": [],
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    },
                },
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "target_column": "FLOAT_COLUMN",
            "training_input": {
                "_max_count": None,
                "_type": {
                    "weight_column": {
                        "_max_count": None,
                        "_type": "INT_COLUMN|FLOAT_COLUMN",
                        "_default": None,
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": True,
                    }
                },
                "_default": {},
                "_min_count": None,
                "_allow_null": False,
                "_optional": True,
            },
            "hparams": {
                "_max_count": None,
                "_type": {
                    "hidden_units": {
                        "_max_count": None,
                        "_type": [
                            {
                                "_max_count": None,
                                "_type": "INT",
                                "_default": None,
                                "_min_count": None,
                                "_allow_null": False,
                                "_optional": False,
                            }
                        ],
                        "_default": None,
                        "_min_count": None,
                        "_allow_null": False,
                        "_optional": False,
                    }
                },
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "prediction_key": "",
            "file_path": "/home/ubuntu/src/github.com/cortexlabs/cortex/pkg/estimators/estimators.yaml",
            "namespace": "cortex",
            "embed": None,
            "path": "dnn_regressor.py",
            "resource_type": "estimator",
            "name": "dnn_regressor",
        }
    },
    "raw_dataset": {
        "key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/data_raw/raw.parquet"
    },
    "aggregators": {
        "cortex.mean": {
            "impl_key": "aggregators/71c8aa1ce07d9d7059e305ed2b180504c36a41452e73fb251ef532bf679f851.py",
            "index": 13,
            "file_path": "/home/ubuntu/src/github.com/cortexlabs/cortex/pkg/aggregators/aggregators.yaml",
            "id": "945acd1e82ed2178b7937215f6f82c814abfa967ec7da545e0a8c776759a37f",
            "input": {
                "_max_count": None,
                "_type": "FLOAT_COLUMN|INT_COLUMN",
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "embed": None,
            "path": "spark/mean.py",
            "resource_type": "aggregator",
            "output_type": "FLOAT",
            "namespace": "cortex",
            "name": "mean",
        },
        "cortex.stddev": {
            "impl_key": "aggregators/b8fa468e54c55083bf350f8b482c5323bd4bc12dd5fa0d859908ab2829aea7f.py",
            "index": 18,
            "file_path": "/home/ubuntu/src/github.com/cortexlabs/cortex/pkg/aggregators/aggregators.yaml",
            "id": "5b076c542b7e8ad7ebd57c1bedad32875ccddccf66bb11c4d87a6058ec765c9",
            "input": {
                "_max_count": None,
                "_type": "FLOAT_COLUMN|INT_COLUMN",
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "embed": None,
            "path": "spark/stddev.py",
            "resource_type": "aggregator",
            "output_type": "FLOAT",
            "namespace": "cortex",
            "name": "stddev",
        },
        "cortex.collect_set_int": {
            "impl_key": "aggregators/4a26fe7551ea175ae68b998ea12766a8e4ffc6a6763816b141bc84d42275e90.py",
            "index": 2,
            "file_path": "/home/ubuntu/src/github.com/cortexlabs/cortex/pkg/aggregators/aggregators.yaml",
            "id": "d35f3139f033053d7cc923869d15501cab7078c31ca023a32e307edaac35ae3",
            "input": {
                "_max_count": None,
                "_type": "INT_COLUMN",
                "_default": None,
                "_min_count": None,
                "_allow_null": False,
                "_optional": False,
            },
            "embed": None,
            "path": "spark/collect_set_int.py",
            "resource_type": "aggregator",
            "output_type": ["INT"],
            "namespace": "cortex",
            "name": "collect_set_int",
        },
    },
    "metadata_root": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/metadata",
    "raw_columns": {
        "raw_string_columns": {
            "smoker": {
                "index": 4,
                "required": True,
                "id": "bc1c3bb3c732a345b258e63cfe5940b83263387400a8ee8dfe2e3da2c3738ba",
                "name": "smoker",
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "STRING_COLUMN",
                "values": ["yes", "no"],
            },
            "region": {
                "index": 5,
                "required": True,
                "id": "50c6020ab96e779616e47299d31be8554951b04b5739e8e2ab6f80f1e1496e6",
                "name": "region",
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "STRING_COLUMN",
                "values": ["northwest", "northeast", "southwest", "southeast"],
            },
            "sex": {
                "index": 1,
                "required": True,
                "id": "f254498c36d334a4d644b9b7e5270a9f11d90d8d813de81c80a4dd26e663080",
                "name": "sex",
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "STRING_COLUMN",
                "values": ["female", "male"],
            },
        },
        "raw_inferred_columns": {},
        "raw_float_columns": {
            "charges": {
                "index": 6,
                "required": True,
                "id": "6d509f4ef30835fa09dd016224b8b5834067891ed1e124437a7cd6a18085f17",
                "name": "charges",
                "max": 100000.0,
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "min": 0.0,
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "FLOAT_COLUMN",
                "values": None,
            },
            "bmi": {
                "index": 2,
                "required": True,
                "id": "3d860159e81a8a135ec9671a5a502dc173baeccc7a53dc864259979babb3cbf",
                "name": "bmi",
                "max": 60.0,
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "min": 0.0,
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "FLOAT_COLUMN",
                "values": None,
            },
        },
        "raw_int_columns": {
            "age": {
                "index": 0,
                "required": True,
                "id": "358aff863718ec09c9cba6c6e35a355b23cf3049a20b91a52227d3f92ece6f0",
                "name": "age",
                "max": 100,
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "min": 0,
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "INT_COLUMN",
                "values": None,
            },
            "children": {
                "index": 3,
                "required": True,
                "id": "0ce7002b9385e30d703d79724b22bff3e82094fcbc479a2cffd90af5362edf4",
                "name": "children",
                "max": 10,
                "workload_id": "f8tzufenx064auff8m0m",
                "tags": {},
                "file_path": "resources/features.yaml",
                "min": 0,
                "embed": None,
                "resource_type": "raw_column",
                "compute": {
                    "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                    "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                    "driver_mem_overhead": None,
                    "executor_mem_overhead": None,
                    "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                    "executors": 1,
                    "mem_overhead_factor": None,
                    "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                },
                "type": "INT_COLUMN",
                "values": None,
            },
        },
    },
    "root": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc",
    "python_packages": {},
    "cortex_config": {
        "id": "a5f22219fb4b739f6e6a2659571fbb971b10586e484e82101f55c307cd4d113",
        "log_group": "cortex",
        "bucket": "cortex-cluster-david",
        "api_version": "master",
        "telemetry_url": "https://telemetry.cortexlabs.dev",
        "enable_telemetry": False,
        "operator_in_cluster": False,
        "namespace": "cortex",
        "region": "us-west-2",
    },
    "id": "0d8a4cae897b48939e171ae4bb392478f9c5828d05dba2477ffc7f431630119",
    "aggregates": {
        "charges_stddev": {
            "index": 8,
            "id": "1ca4af184daac7bba1411b8546b3690fc6c1c679d5396dd67021afcc7f6af2b",
            "input": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges",
            "compute": {
                "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                "driver_mem_overhead": None,
                "executor_mem_overhead": None,
                "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                "executors": 1,
                "mem_overhead_factor": None,
                "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
            },
            "key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/aggregates/1ca4af184daac7bba1411b8546b3690fc6c1c679d5396dd67021afcc7f6af2b.msgpack",
            "workload_id": "f8tzufenx064auff8m0m",
            "aggregator_path": None,
            "tags": {},
            "file_path": "resources/features.yaml",
            "embed": None,
            "resource_type": "aggregate",
            "aggregator": "cortex.stddev",
            "type": "FLOAT",
            "name": "charges_stddev",
        },
        "children_set": {
            "index": 9,
            "id": "95a695c83a3ee200f259d0a4fbbf21df45cb7ddd92b128463e470e8682bf821",
            "input": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dchildren",
            "compute": {
                "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                "driver_mem_overhead": None,
                "executor_mem_overhead": None,
                "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                "executors": 1,
                "mem_overhead_factor": None,
                "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
            },
            "key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/aggregates/95a695c83a3ee200f259d0a4fbbf21df45cb7ddd92b128463e470e8682bf821.msgpack",
            "workload_id": "f8tzufenx064auff8m0m",
            "aggregator_path": None,
            "tags": {},
            "file_path": "resources/features.yaml",
            "embed": None,
            "resource_type": "aggregate",
            "aggregator": "cortex.collect_set_int",
            "type": ["INT"],
            "name": "children_set",
        },
        "charges_mean": {
            "index": 7,
            "id": "c7651ffa3a3093d6825cb81cb6eb4cb00224eafce0b8f0f63316720a55f5067",
            "input": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges",
            "compute": {
                "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                "driver_mem_overhead": None,
                "executor_mem_overhead": None,
                "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                "executors": 1,
                "mem_overhead_factor": None,
                "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
            },
            "key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/aggregates/c7651ffa3a3093d6825cb81cb6eb4cb00224eafce0b8f0f63316720a55f5067.msgpack",
            "workload_id": "f8tzufenx064auff8m0m",
            "aggregator_path": None,
            "tags": {},
            "file_path": "resources/features.yaml",
            "embed": None,
            "resource_type": "aggregate",
            "aggregator": "cortex.mean",
            "type": "FLOAT",
            "name": "charges_mean",
        },
    },
    "environment": {
        "index": 0,
        "file_path": "resources/data.yaml",
        "id": "a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc",
        "name": "dev",
        "log_level": {"spark": "WARN", "tensorflow": "DEBUG"},
        "embed": None,
        "limit": {
            "num_rows": None,
            "random_seed": None,
            "randomize": None,
            "fraction_of_rows": None,
        },
    },
    "models": {
        "dnn": {
            "index": 0,
            "id": "28ff0a1d6793666212edae613152f6f1256045c85c64d2d48e0e15110eecb04",
            "input": {
                "categorical_columns_with_vocab": [
                    {
                        "vocab": ["female", "male"],
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dsex",
                    },
                    {
                        "vocab": ["yes", "no"],
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dsmoker",
                    },
                    {
                        "vocab": ["northwest", "northeast", "southwest", "southeast"],
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dregion",
                    },
                    {
                        "vocab": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dchildren_set",
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dchildren",
                    },
                ],
                "bucketized_columns": [
                    {
                        "boundaries": [15.0, 20.0, 25.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0],
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dage",
                    },
                    {
                        "boundaries": [15.0, 20.0, 25.0, 35.0, 40.0, 45.0, 50.0, 55.0],
                        "col": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dbmi",
                    },
                ],
            },
            "dataset": {
                "index": 0,
                "workload_id": "f8tzufenx064auff8m0m",
                "file_path": "resources/models.yaml",
                "id": "af07374026ff34a45e103b5b18df4be9f3725e8fc40aef62640ba611c0cd2e6",
                "name": "dnn/training_dataset",
                "train_key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/data_training/af07374026ff34a45e103b5b18df4be9f3725e8fc40aef62640ba611c0cd2e6/train.tfrecord",
                "embed": None,
                "eval_key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/data_training/af07374026ff34a45e103b5b18df4be9f3725e8fc40aef62640ba611c0cd2e6/eval.tfrecord",
                "model_name": "dnn",
                "resource_type": "training_dataset",
            },
            "data_partition_ratio": {"evaluation": 0.2, "training": 0.8},
            "key": "apps/insurance/data/2019-06-26-14-08-53-326265/a6a1fa8017ed29aa3a1a6b86f80386f4fcc25ac2367cde81923a662977695bc/models/28ff0a1d6793666212edae613152f6f1256045c85c64d2d48e0e15110eecb04.zip",
            "training_input": None,
            "prediction_key": "",
            "evaluation": {
                "throttle_secs": 600,
                "num_steps": 100,
                "num_epochs": None,
                "batch_size": 40,
                "shuffle": False,
                "start_delay_secs": 120,
            },
            "tags": {},
            "file_path": "resources/models.yaml",
            "workload_id": "odqmsgmpt5plprbbwwcu",
            "training": {
                "tf_randomize_seed": False,
                "num_steps": 10000,
                "keep_checkpoint_every_n_hours": 10000,
                "batch_size": 40,
                "num_epochs": None,
                "save_summary_steps": 100,
                "save_checkpoints_secs": 600,
                "shuffle": True,
                "tf_random_seed": 1788,
                "save_checkpoints_steps": None,
                "log_step_count_steps": 100,
                "keep_checkpoint_max": 3,
            },
            "compute": {"mem": None, "gpu": None, "cpu": None},
            "name": "dnn",
            "target_column": "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges_normalized",
            "estimator": "cortex.dnn_regressor",
            "hparams": {"hidden_units": [100, 100, 100]},
            "estimator_path": None,
            "dataset_compute": {
                "driver_cpu": '{"Quantity":"1","UserString":"1"}',
                "driver_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
                "driver_mem_overhead": None,
                "executor_mem_overhead": None,
                "executor_cpu": '{"Quantity":"1","UserString":"1"}',
                "executors": 1,
                "mem_overhead_factor": None,
                "executor_mem": '{"Quantity":"500Mi","UserString":"500Mi"}',
            },
            "embed": None,
            "resource_type": "model",
        }
    },
    "environment_data": {
        "parquet_data": None,
        "csv_data": {
            "type": "csv",
            "drop_null": False,
            "csv_config": {
                "escape": None,
                "comment": None,
                "header": None,
                "max_columns": None,
                "nan_value": None,
                "negative_inf": None,
                "multiline": None,
                "null_value": None,
                "encoding": None,
                "sep": None,
                "empty_value": None,
                "ignore_leading_white_space": None,
                "max_chars_per_column": None,
                "ignore_trailing_white_space": None,
                "positive_inf": None,
                "char_to_escape_quote_escaping": None,
                "quote": None,
            },
            "path": "s3a://cortex-examples/insurance.csv",
            "schema": [
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dage",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dsex",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dbmi",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dchildren",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dsmoker",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dregion",
                "\U0001f31d\U0001f31d\U0001f31d\U0001f31d\U0001f31dcharges",
            ],
        },
    },
}
