# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import generator_pb2 as generator__pb2


class GeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_stream(
            "/prime_generator.Generator/Predict",
            request_serializer=generator__pb2.Input.SerializeToString,
            response_deserializer=generator__pb2.Output.FromString,
        )


class GeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Predict": grpc.unary_stream_rpc_method_handler(
            servicer.Predict,
            request_deserializer=generator__pb2.Input.FromString,
            response_serializer=generator__pb2.Output.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "prime_generator.Generator", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Generator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/prime_generator.Generator/Predict",
            generator__pb2.Input.SerializeToString,
            generator__pb2.Output.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
