apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: apis-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    istio: ingressgateway-apis
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTP
      hosts:
        - "*"
