- kind: app
  name: poker

- kind: environment
  name: dev
  data:
    type: csv
    path: s3a://cortex-examples/poker.csv
    schema: [@card_1_suit, @card_1_rank, @card_2_suit, @card_2_rank, @card_3_suit, @card_3_rank, @card_4_suit, @card_4_rank, @card_5_suit, @card_5_rank, @class]

- kind: model
  name: dnn
  estimator: cortex.dnn_classifier
  target_column: @class
  input:
    num_classes: 10
    categorical_columns_with_vocab:
      - col: @card_1_suit
        vocab: [1, 2, 3, 4]
      - col: @card_1_rank
        vocab: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      - col: @card_2_suit
        vocab: [1, 2, 3, 4]
      - col: @card_2_rank
        vocab: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      - col: @card_3_suit
        vocab: [1, 2, 3, 4]
      - col: @card_3_rank
        vocab: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      - col: @card_4_suit
        vocab: [1, 2, 3, 4]
      - col: @card_4_rank
        vocab: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      - col: @card_5_suit
        vocab: [1, 2, 3, 4]
      - col: @card_5_rank
        vocab: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  hparams:
    hidden_units: [100, 100, 100, 100, 100]
  training:
    num_steps: 20000

- kind: api
  name: hand
  model: @dnn
