apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-nodeagent-{{ .Release.Namespace }}
  labels:
    app: {{ template "nodeagent.name" . }}
    chart: {{ template "nodeagent.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]