apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-security-custom-resources
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "security.name" . }}
    chart: {{ template "security.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: citadel
data:
  custom-resources.yaml: |-
    {{- if .Values.global.mtls.enabled }}
      {{- include "security-default.yaml.tpl" . | indent 4}}
    {{- else }}
      {{- include "security-permissive.yaml.tpl" . | indent 4}}
    {{- end }}
  run.sh: |-
    {{- include "install-custom-resources.sh.tpl" . | indent 4}}
