apiVersion: v1
name: istio-init
version: 1.2.2
appVersion: 1.2.2
tillerVersion: ">=2.7.2-0"
description: Helm chart to initialize Istio CRDs
keywords:
  - istio
  - crd
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
