- kind: model
  name: dnn
  type: classification
  target: class_indexed
  features:
    - sepal_length_normalized
    - sepal_width_normalized
    - petal_length_normalized
    - petal_width_normalized
  hparams:
    hidden_units: [4, 2]
  data_partition_ratio:
    training: 0.9
    evaluation: 0.1
  training:
    batch_size: 10
    num_steps: 1000
  aggregates:
    - class_index
