- kind: model
  name: dnn
  type: classification
  target_column: INT
  inputs:
    normalized_columns: INT_COLUMN|FLOAT_COLUMN
    class_index: [STRING]
  default_hparams:
    hidden_units: [4, 2]

- kind: trainer
  name: dnn-base
  model: dnn
  target_column: class_indexed
  inputs:
    nomralized_columns:
      - sepal_length_normalized
      - sepal_width_normalized
      - petal_length_normalized
      - petal_width_normalized
    class_index:
      - class_index
  data_partition_ratio:
    training: 80
    evaluation: 20
  training:
    batch_size: 10
    num_steps: 1000
