- kind: model
  name: dnn
  estimator_path: implementations/models/dnn.py
  target_column: @class_indexed
  input:
    cols:
      - @sepal_length_normalized
      - @sepal_width_normalized
      - @petal_length_normalized
      - @petal_width_normalized
    num_classes: 3
  hparams:
    hidden_units: [4, 2]
  data_partition_ratio:
    training: 80
    evaluation: 20
  training:
    batch_size: 10
    num_steps: 1000
