apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 8080
    name: http-legacy-discovery # direct
  - port: {{ .Values.global.monitoringPort }}
    name: http-monitoring
  selector:
    istio: pilot
