# Copyright 2021 Cortex Labs, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://github.com/encode/uvicorn/pull/515/files
# https://github.com/encode/uvicorn/issues/511
# https://github.com/encode/uvicorn/issues/491

version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": cortex_internal.lib.log.CortexFormatter
    format: "%(asctime)s:cortex:pid-%(process)d:%(levelname)s:%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S.%f"
  uvicorn_access:
    "()": cortex_internal.lib.log.CortexAccessFormatter
    format: "%(asctime)s:cortex:pid-%(process)d:%(levelname)s:%(status_code)s %(method)s %(path)s"
    datefmt: "%Y-%m-%d %H:%M:%S.%f"
handlers:
  default:
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
  uvicorn_access:
    formatter: uvicorn_access
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  cortex:
    level: $CORTEX_LOG_LEVEL
    handlers:
      - default
    propagate: no
  uvicorn:
    level: $CORTEX_LOG_LEVEL
    handlers:
      - default
    propagate: no
  uvicorn.error:
    level: $CORTEX_LOG_LEVEL
    handlers:
      - default
    propagate: no
  uvicorn.uvicorn_access:
    level: $CORTEX_LOG_LEVEL
    handlers:
      - uvicorn_access
    propagate: no
