{{- range $key, $spec := .Values }}
{{- if or (eq $key "policy") (eq $key "telemetry") }}
{{- if $spec.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: istio-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  annotations:
   networking.istio.io/exportTo: "*"
  labels:
    app: {{ template "mixer.name" $ }}
    chart: {{ template "mixer.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
    istio: mixer
spec:
  ports:
  - name: grpc-mixer
    port: 9091
  - name: grpc-mixer-mtls
    port: 15004
  - name: http-monitoring
    port: {{ $.Values.global.monitoringPort }}
{{- if eq $key "telemetry" }}
  - name: prometheus
    port: 42422
{{- if $spec.sessionAffinityEnabled }}
  sessionAffinity: ClientIP
{{- end }}
{{- end }}
  selector:
    istio: mixer
    istio-mixer-type: {{ $key }}
---
{{- end }}
{{- end }}
{{- end }}

