{
 "title": "Cortex",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cortex Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">Cortex Dashboard</h1>"
   }
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Rate of all responses by API, for all API IDs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-.*\", response_code=~\"2.*\"}[5m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "graph",
   "description": "Rate of 2XX status codes returned by API, for all API IDs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-.*\", response_code=~\"2.*\"}[5m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "graph",
   "description": "Rate of 4XX status codes returned by API, for all API IDs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-.*\", response_code=~\"4.*\"}[5m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "graph",
   "description": "Rate of 5XX status codes returned by API, for all API IDs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-.*\", response_code=~\"5.*\"}[5m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "graph",
   "description": "99th percentile for request latency per API, for all API IDs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-.*\"}[5m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "graph",
   "description": "90th percentile for request latency per API, for all API IDs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-.*\"}[5m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "graph",
   "description": "50th percentile for request latency per API, for all API IDs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum without (response_code) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-.*\"}[5m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "Average request latency per API, for all API IDs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "  sum without (response_code) (rate(istio_request_duration_milliseconds_sum{destination_service_name=~\"api-.*\"}[5m]))\n/\n  sum without (response_code) (rate(istio_request_duration_milliseconds_count{destination_service_name=~\"api-.*\"}[5m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}