{
 "title": "RealtimeAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "api_name",
    "label": "API Name",
    "query": {
     "query": "label_values(cortex_in_flight_requests{api_kind=\"RealtimeAPI\"}, api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">RealtimeAPI</h1>"
   }
  },
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Request rate, computed over every minute, of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "graph",
   "description": "Active in-flight requests for an API.\n\nNote: In-flight requests are recorded every 10 seconds, which will correspond to the minimum resolution.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_in_flight_requests{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 2XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"2.*\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Active Replicas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(cortex_in_flight_requests{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 4XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"4.+\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "graph",
   "description": "Request rate, computed over every minute, for responses with status code 5XX of an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_service_name=~\"api-$api_name.+\", response_code=~\"5.+\"}[1m])) by (destination_service_name, response_code)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "graph",
   "description": "99th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (destination_service_name, le) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "graph",
   "description": "90th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (destination_service_name, le) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "graph",
   "description": "50th percentile latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (destination_service_name, le) (rate(istio_request_duration_milliseconds_bucket{destination_service_name=~\"api-$api_name.+\"}[1m])))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "graph",
   "description": "Average latency, computed over a minute, for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name) / sum(rate(istio_request_duration_milliseconds_count{destination_service_name=~\"api-$api_name.+\"}[1m])) by (destination_service_name)",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  { "title": "Aggregate Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "description": "Total CPU usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "core", "label": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"api-$api_name.+\", container!=\"POD\", name!=\"\"}[1m]))",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"api-$api_name.+\"})",
     "legendFormat": "Total CPU Request"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{pod=~\"api-$api_name.+\", name!=\"\", container!=\"POD\"}[1m]))\n/\nsum(count_over_time(container_memory_working_set_bytes{pod=~\"api-$api_name.+\", name!=\"\", container=\"api\"}[1m])) / 1024^2",
     "legendFormat": "Total Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"api-$api_name.+\"}) / 1024^2",
     "legendFormat": "Total Memory Request"
    }
   ]
  },
  {
   "title": "Total GPU Core Usage",
   "type": "graph",
   "description": "Total GPU core usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "gpuCore", "label": "gpu" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"api-$api_name.+\"}) / 100",
     "legendFormat": "Total GPU Usage"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"api-$api_name.+\"})",
     "legendFormat": "Total GPU Capacity"
    }
   ]
  },
  {
   "title": "Total GPU Memory Usage",
   "type": "graph",
   "description": "Total GPU memory usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"api-$api_name.+\"})",
     "legendFormat": "Total Used GPU Memory"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_FREE{exported_pod=~\"api-$api_name.+\"}) + sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"api-$api_name.+\"})",
     "legendFormat": "Total Capacity GPU Memory"
    }
   ]
  },
  { "title": "Average Replica Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Avg CPU Usage",
   "type": "graph",
   "description": "Avg CPU usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "core", "label": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"api-$api_name.+\", container!=\"POD\", name!=\"\"}[1m]))\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=~\"api-$api_name.+\"})\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg CPU Request"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "graph",
   "description": "Avg memory usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{pod=~\"api-$api_name.+\", name!=\"\", container!=\"POD\"}[1m]))\n/\nsum(count_over_time(container_memory_working_set_bytes{pod=~\"api-$api_name.+\", name!=\"\", container=\"api\"}[1m])) / 1024^2\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=~\"api-$api_name.+\"}) / 1024^2\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg Memory Request"
    }
   ]
  },
  {
   "title": "Avg GPU Core Usage",
   "type": "graph",
   "description": "Avg GPU core usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "gpuCore", "label": "gpu" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"api-$api_name.+\"}) / 100\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg GPU Usage"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"api-$api_name.+\"})\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg GPU Capacity"
    }
   ]
  },
  {
   "title": "Avg GPU Memory Usage",
   "type": "graph",
   "description": "Avg GPU memory usage across all replicas of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"api-$api_name.+\"})\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg Used GPU Memory"
    },
    {
     "expr": "(sum(DCGM_FI_DEV_FB_FREE{exported_pod=~\"api-$api_name.+\"}) + sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"api-$api_name.+\"}))\n/\ncount(cortex_in_flight_requests{api_name=~\"$api_name\"})",
     "legendFormat": "Avg Capacity GPU Memory"
    }
   ]
  }
 ]
}