{
 "title": "BatchAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "api_name",
    "label": "API Name",
    "query": {
     "query": "label_values({__name__=~\"cortex_batch_.+\"}, api_name)"
    }
   },
   {
    "name": "api_pod_names",
    "label": "API Pod Names",
    "query": {
     "query": "query_result(sum(kube_pod_container_status_running{exported_pod=~\"$api_name.+\"}) by (exported_pod))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">BatchAPI</h1>\n"
   }
  },
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "# Succeeded Batches",
   "type": "graph",
   "description": "Number of succeeded batches for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_batch_succeeded{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "# Failed Batches",
   "type": "graph",
   "description": "Number of failed batches for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_batch_failed{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Average Time per Batch",
   "type": "graph",
   "description": "Average time per batch for an API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_time_per_batch_sum{api_name=~\"$api_name\"}) by (api_name) / sum(cortex_time_per_batch_count{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Job Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "CPU usage for a given worker",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "repeat": "api_pod_names",
     "yaxes": [
      { "format": "core", "label": "cpu" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{exported_pod=\"$api_pod_names\"})",
       "legendFormat": "CPU Request on $api_pod_names"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"$api_pod_names\", container!=\"POD\", name!=\"\"}[1m]))",
       "legendFormat": "CPU Usage on $api_pod_names"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Memory usage for a given worker",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "repeat": "api_pod_names",
     "yaxes": [
      { "format": "MiB", "label": "memory" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{exported_pod=\"$api_pod_names\"}) / 1024^2",
       "legendFormat": "Memory Request on $api_pod_names"
      },
      {
       "expr": "sum(sum_over_time(container_memory_working_set_bytes{pod=\"$api_pod_names\", name!=\"\", container!=\"POD\"}[1m]))\n/\nsum(count_over_time(container_memory_working_set_bytes{pod=\"$api_pod_names\", name!=\"\", container=\"api\"}[1m])) / 1024^2",
       "legendFormat": "Memory Usage on $api_pod_names"
      }
     ]
    },
    {
     "title": "GPU Core Utilization",
     "type": "graph",
     "description": "GPU core utilization for a given worker",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
     "repeat": "api_pod_names",
     "yaxes": [
      { "format": "gpuCore", "label": "gpu" }
     ],
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_pod=\"$api_pod_names\"}) / 100",
       "legendFormat": "GPU Utilization on $api_pod_names"
      }
     ]
    },
    {
     "title": "GPU Memory Utilization",
     "type": "graph",
     "description": "GPU memory utilization for a given worker",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
     "repeat": "api_pod_names",
     "yaxes": [
      { "format": "MiB", "label": "memory" }
     ],
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=\"$api_pod_names\"})",
       "legendFormat": "GPU Used on $api_pod_names"
      },
      {
       "expr": "sum(DCGM_FI_DEV_FB_FREE{exported_pod=\"$api_pod_names\"}) + sum(DCGM_FI_DEV_FB_USED{exported_pod=\"$api_pod_names\"})",
       "legendFormat": "Capacity GPU Memory on $api_pod_names"
      }
     ]
    }
   ]
  }
 ]
}