{
 "title": "TaskAPI",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "api_name",
    "label": "API Name",
    "query": {
     "query": "label_values({__name__=~\"cortex_task_.+\"}, api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center\">TaskAPI</h1>\n"
   }
  },
  { "title": "API Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "# Succeeded Tasks",
   "type": "graph",
   "description": "Number of succeeded tasks for an API",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_task_succeeded{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "# Failed Tasks",
   "type": "graph",
   "description": "Number of failed tasks for an API",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_task_failed{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Average Time per Task",
   "type": "graph",
   "description": "Average time per task for an API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(cortex_time_per_task_sum{api_name=~\"$api_name\"}) by (api_name) / sum(cortex_time_per_task_count{api_name=~\"$api_name\"}) by (api_name)",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "# Active Tasks",
   "type": "graph",
   "description": "Active tasks",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "count(kube_job_status_active{job_name=~\"$api_name.+\"} != 0)",
     "legendFormat": "Active Tasks"
    }
   ]
  },
  { "title": "Aggregate Worker Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total CPU Usage",
   "type": "graph",
   "description": "Total CPU usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "core", "label": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$api_name.+\", container!=\"POD\", name!=\"\"}[1m]))",
     "legendFormat": "Total CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{exported_pod=~\"$api_name.+\", resource=\"cpu\"})",
     "legendFormat": "Total CPU Request"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "description": "Total memory usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{pod=~\"$api_name.+\", name!=\"\", container!=\"POD\"}[1m]))\n/\navg(count_over_time(container_memory_working_set_bytes{pod=~\"$api_name.+\", name!=\"\", container=\"api\"}[1m])) / 1024^2",
     "legendFormat": "Total Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{exported_pod=~\"$api_name.+\", resource=\"memory\"}) / 1024^2",
     "legendFormat": "Total Memory Request"
    }
   ]
  },
  {
   "title": "Total GPU Core Usage",
   "type": "graph",
   "description": "Total GPU core usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "gpuCore", "label": "gpu" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"}) / 100",
     "legendFormat": "Total GPU Usage"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Total GPU Capacity"
    }
   ]
  },
  {
   "title": "Total GPU Memory Usage",
   "type": "graph",
   "description": "Total GPU memory usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Total Used GPU Memory"
    },
    {
     "expr": "sum(DCGM_FI_DEV_FB_FREE{exported_pod=~\"$api_name.+\"}) + sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Total Capacity GPU Memory"
    }
   ]
  },
  { "title": "Avg Worker Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Avg CPU Usage",
   "type": "graph",
   "description": "Avg CPU usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "core", "label": "cpu" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$api_name.+\", container!=\"POD\", name!=\"\"}[1m]))\n/\nsum(kube_pod_info{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{exported_pod=~\"$api_name.+\", resource=\"cpu\"})\n/\nsum(kube_pod_info{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg CPU Request"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "graph",
   "description": "Avg memory usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(container_memory_working_set_bytes{pod=~\"$api_name.+\", name!=\"\", container!=\"POD\"}[1m]))\n/\navg(count_over_time(container_memory_working_set_bytes{pod=~\"$api_name.+\", name!=\"\", container=\"api\"}[1m])) / 1024^2\n/\nsum(kube_pod_info{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource{exported_pod=~\"$api_name.+\", resource=\"memory\"}) / 1024^2\n/\nsum(kube_pod_info{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg Memory Request"
    }
   ]
  },
  {
   "title": "Avg GPU Core Usage",
   "type": "graph",
   "description": "Avg GPU core usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "gpuCore", "label": "gpu" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"}) / 100\n/\ncount(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg GPU Usage"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"})\n/\ncount(count(DCGM_FI_DEV_GPU_UTIL{exported_pod=~\"$api_name.+\"}) by (exported_pod))",
     "legendFormat": "Avg GPU Capacity"
    }
   ]
  },
  {
   "title": "Avg GPU Memory Usage",
   "type": "graph",
   "description": "Avg GPU memory usage across all workers of the API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "MiB", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"})\n/\ncount(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg Used GPU Memory"
    },
    {
     "expr": "(sum(DCGM_FI_DEV_FB_FREE{exported_pod=~\"$api_name.+\"}) + sum(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"}))\n/\ncount(DCGM_FI_DEV_FB_USED{exported_pod=~\"$api_name.+\"})",
     "legendFormat": "Avg Capacity GPU Memory"
    }
   ]
  }
 ]
}