- kind: model
  name: dnn
  estimator: cortex.dnn_classifier
  target_column: @quality_bucketized
  input:
    num_classes: 2
    numeric_columns: [@fixed_acidity, @volatile_acidity, @citric_acid, @residual_sugar, @chlorides, @free_sulfur_dioxide, @total_sulfur_dioxide, @density, @pH, @sulphates, @alcohol]
  hparams:
    hidden_units: [100, 100, 100, 100, 100]
  data_partition_ratio:
    training: 80
    evaluation: 20
  training:
    batch_size: 64
    num_steps: 10000
