# use temporary fix until https://github.com/kubernetes/autoscaler/issues/3095
# gets in the next release of the k8s autoscaler
# FROM robertlucian/cortexlabs-cluster-autoscaler:v1.15.7-85284e6

FROM us.gcr.io/k8s-artifacts-prod/autoscaling/cluster-autoscaler:v1.16.5