# Version obtained from https://github.com/aws/aws-neuron-sdk/issues/102
# Keep an eye on the image's digest over time
FROM 790709498068.dkr.ecr.us-east-1.amazonaws.com/neuron-device-plugin:1.0.6554.0
