# Track the evolution of https://github.com/aws/aws-neuron-sdk/issues/102 ticket
# Once solved, image will have to be replaced with the official, versioned image
FROM robertlucian/cortexlabs-inferentia:2020-04-21
