apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: event-exporter

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: default
    name: event-exporter

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-config
  namespace: default
data:
  config.yaml: |
    logLevel: error
    logFormat: json
    route:
      routes:
        - match:
            - receiver: "stdout"
              labels:
                apiKind: RealtimeAPI
        - match:
            - receiver: "stdout"
              labels:
                apiKind: BatchAPI
        - match:
            - receiver: "stdout"
              labels:
                apiKind: TaskAPI
    receivers:
      - name: "stdout"
        file:
          path: "/dev/stdout"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-exporter
  template:
    metadata:
      labels:
        app: event-exporter
    spec:
      serviceAccountName: event-exporter
      containers:
        - name: event-exporter
          image: $CORTEX_IMAGE_EVENT_EXPORTER
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: event-exporter-config
      volumes:
        - name: event-exporter-config
          configMap:
            name: event-exporter-config
