# Copyright 2016 The prometheus-operator Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Modifications Copyright 2022 Cortex Labs, Inc.

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/version: 1.5.0
  name: node-exporter
  namespace: prometheus

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/version: 1.5.0
  name: node-exporter
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/version: 1.5.0
  name: node-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-exporter
subjects:
  - kind: ServiceAccount
    name: node-exporter
    namespace: prometheus

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 1.5.0
  name: node-exporter
  namespace: prometheus
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9100
      targetPort: https
  selector:
    app.kubernetes.io/name: node-exporter

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 1.5.0
  name: node-exporter
  namespace: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/version: 1.5.0
    spec:
      containers:
        - args:
            - --web.listen-address=127.0.0.1:9100
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
            - --collector.netdev.device-exclude=^(veth.*)$
          image: $CORTEX_IMAGE_PROMETHEUS_NODE_EXPORTER
          name: node-exporter
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 40m
              memory: 180Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - SYS_TIME
              drop:
              - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /host/sys
              mountPropagation: HostToContainer
              name: sys
              readOnly: true
            - mountPath: /host/root
              mountPropagation: HostToContainer
              name: root
              readOnly: true
        - args:
            - --logtostderr
            - --secure-listen-address=[$(IP)]:9100
            - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
            - --upstream=http://127.0.0.1:9100/
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: $CORTEX_IMAGE_KUBE_RBAC_PROXY
          name: kube-rbac-proxy
          ports:
            - containerPort: 9100
              hostPort: 9100
              name: https
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: node-exporter
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /sys
          name: sys
        - hostPath:
            path: /
          name: root
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 1.5.0
    monitoring.cortex.dev: node-exporter
  name: node-exporter
  namespace: prometheus
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      port: https
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
      metricRelabelings:
        - action: keep
          sourceLabels: [__name__]
          regex: "node_(\
            cpu_seconds_total|\
            load1|\
            load5|\
            load15|\
            exporter_build_info|\
            memory_MemTotal_bytes|\
            memory_MemFree_bytes|\
            memory_Buffers_bytes|\
            memory_Cached_bytes|\
            memory_MemAvailable_bytes|\
            disk_read_bytes_total|\
            disk_written_bytes_total|\
            disk_io_time_seconds_total|\
            disk_io_time_weighted_seconds_total|\
            filesystem_size_bytes|\
            filesystem_avail_bytes|\
            network_receive_bytes_total|\
            network_transmit_bytes_total|\
            network_receive_drop_total|\
            network_transmit_drop_total|\
            vmstat_pgmajfault\
            )"
        - action: labelkeep
          regex: (__name__|instance|job|device|fstype|mountpoint|mode)
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter

---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: 1.5.0
    prometheus: k8s
  name: node-exporter-rules
  namespace: prometheus
spec:
  groups:
    - name: node-exporter.rules
      rules:
        - expr: |
            count without (cpu) (
              count without (mode) (
                node_cpu_seconds_total{job="node-exporter"}
              )
            )
          record: instance:node_num_cpu:sum
        - expr: |
            1 - avg without (cpu, mode) (
              rate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[1m])
            )
          record: instance:node_cpu_utilisation:rate1m
        - expr: |
            (
              node_load1{job="node-exporter"}
            /
              instance:node_num_cpu:sum{job="node-exporter"}
            )
          record: instance:node_load1_per_cpu:ratio
        - expr: |
            1 - (
              node_memory_MemAvailable_bytes{job="node-exporter"}
            /
              node_memory_MemTotal_bytes{job="node-exporter"}
            )
          record: instance:node_memory_utilisation:ratio
        - expr: |
            rate(node_vmstat_pgmajfault{job="node-exporter"}[1m])
          record: instance:node_vmstat_pgmajfault:rate1m
        - expr: |
            rate(node_disk_io_time_seconds_total{job="node-exporter", device=~"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+"}[1m])
          record: instance_device:node_disk_io_time_seconds:rate1m
        - expr: |
            rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device=~"mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+"}[1m])
          record: instance_device:node_disk_io_time_weighted_seconds:rate1m
        - expr: |
            sum without (device) (
              rate(node_network_receive_bytes_total{job="node-exporter", device!="lo"}[1m])
            )
          record: instance:node_network_receive_bytes_excluding_lo:rate1m
        - expr: |
            sum without (device) (
              rate(node_network_transmit_bytes_total{job="node-exporter", device!="lo"}[1m])
            )
          record: instance:node_network_transmit_bytes_excluding_lo:rate1m
        - expr: |
            sum without (device) (
              rate(node_network_receive_drop_total{job="node-exporter", device!="lo"}[1m])
            )
          record: instance:node_network_receive_drop_excluding_lo:rate1m
        - expr: |
            sum without (device) (
              rate(node_network_transmit_drop_total{job="node-exporter", device!="lo"}[1m])
            )
          record: instance:node_network_transmit_drop_excluding_lo:rate1m
        - expr: |
            sum (
              (
                instance:node_cpu_utilisation:rate1m{job="node-exporter"}
              *
                instance:node_num_cpu:sum{job="node-exporter"}
              )
              / scalar(sum(instance:node_num_cpu:sum{job="node-exporter"}))
            )
          record: cluster:cpu_utilization:ratio
        - expr: |
            sum (
              instance:node_load1_per_cpu:ratio{job="node-exporter"}
              / scalar(count(instance:node_load1_per_cpu:ratio{job="node-exporter"}))
            )
          record: cluster:load1:ratio
        - expr: |
            sum (
              instance:node_memory_utilisation:ratio{job="node-exporter"}
              / scalar(count(instance:node_memory_utilisation:ratio{job="node-exporter"}))
            )
          record: cluster:memory_utilization:ratio
        - expr: |
            sum (
              instance:node_vmstat_pgmajfault:rate1m{job="node-exporter"}
            )
          record: cluster:vmstat_pgmajfault:rate1m
        - expr: |
            sum (instance:node_network_receive_bytes_excluding_lo:rate1m{job="node-exporter"})
          record: cluster:network_receive_bytes_excluding_low:rate1m
        - expr: |
            sum (instance:node_network_transmit_bytes_excluding_lo:rate1m{job="node-exporter"})
          record: cluster:network_transmit_bytes_excluding_lo:rate1m
        - expr: |
            sum (instance:node_network_receive_drop_excluding_lo:rate1m{job="node-exporter"})
          record: cluster:network_receive_drop_excluding_lo:rate1m
        - expr: |
            sum (instance:node_network_transmit_drop_excluding_lo:rate1m{job="node-exporter"})
          record: cluster:network_transmit_drop_excluding_lo:rate1m
        - expr: |
            sum (
              instance_device:node_disk_io_time_seconds:rate1m{job="node-exporter"}
              / scalar(count(instance_device:node_disk_io_time_seconds:rate1m{job="node-exporter"}))
            )
          record: cluster:disk_io_utilization:ratio
        - expr: |
            sum (
              instance_device:node_disk_io_time_weighted_seconds:rate1m{job="node-exporter"}
              / scalar(count(instance_device:node_disk_io_time_weighted_seconds:rate1m{job="node-exporter"}))
            )
          record: cluster:disk_io_saturation:ratio
        - expr: |
            sum (
              max without (fstype, mountpoint) (
                node_filesystem_size_bytes{job="node-exporter", fstype!=""} - node_filesystem_avail_bytes{job="node-exporter", fstype!=""}
              )
            )
            / scalar(sum(max without (fstype, mountpoint) (node_filesystem_size_bytes{job="node-exporter", fstype!=""})))
          record: cluster:disk_space_utilization:ratio
