- kind: model
  name: basic_embedding
  estimator_path: implementations/models/basic_embedding.py
  target_column: @rating
  input: 
    embedding_columns:
      - col: @user_id_indexed
        vocab: @user_id_index
      - col: @movie_id_indexed
        vocab: @movie_id_index
  hparams:
    embedding_size: 20
    hidden_units: [10, 10]
  data_partition_ratio:
    training: 0.8
    evaluation: 0.2
  training:
    batch_size: 50
    num_steps: 8000
