apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "istiocoredns.name" . }}
    chart: {{ template "istiocoredns.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  Corefile: |
    .:53 {
          errors
          health
          proxy global 127.0.0.1:8053 {
            protocol grpc insecure
          }
          prometheus :9153
          proxy . /etc/resolv.conf
          cache 30
          reload
        }
---
