apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-statsd-exporter-config
  namespace: {{ .Release.Namespace }}
data:
  statsd-mapping.yaml: |
    defaults:
      observer_type: histogram

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prometheus-statsd-exporter
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: prometheus-statsd-exporter
  template:
    metadata:
      labels:
        name: prometheus-statsd-exporter
    spec:
      containers:
        - name: prometheus-statsd-exporter
          image: {{ .Values.cortex.image_prometheus_statsd_exporter }}
          imagePullPolicy: Always
          args:
            - --web.listen-address=:9102
            - --web.telemetry-path=/metrics
            - --statsd.listen-udp=:9125
            - --statsd.listen-tcp=:9125
            - --statsd.cache-size=1000
            - --statsd.event-queue-size=10000
            - --statsd.event-flush-threshold=1000
            - --statsd.event-flush-interval=200ms
            - --statsd.mapping-config=/etc/prometheus-statsd-exporter/statsd-mapping.yaml
          ports:
            - name: metrics
              containerPort: 9102
              protocol: TCP
            - name: statsd-udp
              containerPort: 9125
              hostPort: 9125
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: statsd-mapping-config
              mountPath: /etc/prometheus-statsd-exporter
      volumes:
        - name: statsd-mapping-config
          configMap:
            name: prometheus-statsd-exporter-config
            items:
              - key: statsd-mapping.yaml
                path: statsd-mapping.yaml
      terminationGracePeriodSeconds: 60
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: workload
          operator: Exists
          effect: NoSchedule
