# Sources:
# https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/master/k8s-yaml-templates/cwagent-statsd/cwagent-statsd-daemonset.yaml
# https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/master/k8s-yaml-templates/cwagent-statsd/cwagent-statsd-configmap.yaml

{{- if eq .Values.global.provider "aws" }}
apiVersion: v1
data:
  cwagentconfig.json: |
    {
      "agent": {
        "omit_hostname": true,
        "region": {{ .Values.cortex.region | quote }}
      },
      "metrics": {
        "namespace": {{ .Values.cortex.cluster_name | quote }},
        "force_flush_interval": 1,
        "metrics_collected": {
          "statsd": {
            "service_address":":8125",
            "metrics_collection_interval": 1,
            "metrics_aggregation_interval": 1
          }
        }
      }
    }
kind: ConfigMap
metadata:
  name: cwagentstatsdconfig
  namespace: {{ .Release.Namespace }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: statsd
value: 1000
globalDefault: false
description: "This priority class should be used for statsd daemonset only."
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent-statsd
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: cloudwatch-agent-statsd
  template:
    metadata:
      labels:
        name: cloudwatch-agent-statsd
    spec:
      priorityClassName: statsd
      containers:
        - name: cloudwatch-agent
          image: {{ .Values.cortex.image_statsd }}
          imagePullPolicy: Always
          ports:
            # containerPort should be consistent with the listen port defined in configmap
            - containerPort: 8125
              hostPort: 8125
              protocol: UDP
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          # Please don't change the env
          env:
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: AWS_REGION
              value: {{ .Values.cortex.region }}
          envFrom:
            - secretRef:
                name: aws-credentials
          # Please don't change the mountPath
          volumeMounts:
            - name: cwagentconfig
              mountPath: /etc/cwagentconfig
      volumes:
        - name: cwagentconfig
          configMap:
            name: cwagentstatsdconfig
      terminationGracePeriodSeconds: 60
      tolerations:
        - key: aws.amazon.com/neuron
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
        - key: workload
          operator: Exists
          effect: NoSchedule
{{- end }}
