apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |
    istio_namespace: {{ .Release.Namespace }}
    auth:
      strategy: "login"
    server:
      port: 20001
{{- if .Values.contextPath }}
      web_root: {{ .Values.contextPath }}
{{- end }}
    external_services:
      tracing:
        url: {{ .Values.dashboard.jaegerURL }}
      grafana:
        url: {{ .Values.dashboard.grafanaURL }}
      prometheus:
        url: {{ .Values.prometheusAddr }}
