{{- if .Values.createDemoSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboard.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  username: YWRtaW4=   # admin
  passphrase: YWRtaW4= # admin
{{- end }}
