apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-grafana-custom-resources
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: grafana
data:
  custom-resources.yaml: |-
    {{- include "grafana-default.yaml.tpl" . | indent 4}}
  run.sh: |-
    {{- include "install-custom-resources.sh.tpl" . | indent 4}}
